name: ag_appointment
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  intl: ^0.18.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.11
  riverpod_annotation: ^1.0.6
  image_picker: ^0.8.6
  animations: ^2.0.7
  file_picker: ^5.2.4
  country_picker: ^2.0.19
  permission_handler: ^10.2.0
  flutter_contacts: ^1.1.5+1
  image_cropper: ^3.0.1
  cached_memory_image: ^1.3.1

  
 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
